### ISSUE TITLE
Apply Discount Code by JavaScript jumbles styles/class names in html if using Custom Level Cost Text 

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-level-cost-text#11]
A support user was trying to put standard HTML with two classes in the entity when using the Custom Level Cost Text Add On.

When you enter a discount code and click to apply the code, the styles/class names are being restructured.

To replicate, use custom level cost text for your discount code like:
`<span class="firstclass secondclass"> $10 per month! </span>`

Apply the code at checkout and use web inspector to see how the class names are incorrect.

**Comment by JarrydLong** [comment]
I've run a couple of tests with PMPro 2.9.8 and the Custom Level Cost Text Add On 0.3.2 and can confirm that this issue no longer occurs. The same classes/structure remain even after applying a discount. 

Screenshot of before:

![image](https://user-images.githubusercontent.com/8989542/211799346-df48f268-6ba0-4fd5-a9d1-fbc49bb5d7ed.png)


Screenshot of after: 

![image](https://user-images.githubusercontent.com/8989542/211799428-632315be-1826-42a4-8b25-ee44eead6647.png)
