### ISSUE TITLE
Setting "Hide Decimals" to Yes causes recurring subscription to show only the initial payment

### ISSUE THREAD

**Issue by MaryOJob** [strangerstudios/pmpro-level-cost-text#13]
Steps to recreate:
- Activate the Level Cost Text add-on
- Set the number of billing cycle to 1 or more, the default text cost should be "The price for membership is $10.00 now and then $10.00 after 1 Year."
- Go to advanced settings under membership, and set the Hide Unnecessary Decimals to "Yes"
- The default text cost becomes "The price for membership is $10"

For Moderators Only: https://www.paidmembershipspro.com/forums/topic/level-cost-text-add-on-not-working-with-payment-plan-discount-code-method/

PS: Whether or not [this discount code](https://www.paidmembershipspro.com/add-a-payment-plan-to-a-pmpro-checkout-page/) method is used, the issue persists.

**Comment by dparker1005** [comment]
Similar issue here: https://www.paidmembershipspro.com/improve-levels-pricing-statement-custom-level-cost-text-add/#comment-45468
