### ISSUE TITLE
Bug: Does not change text when using Group Discount Code Add On.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-level-cost-text#16]
The Custom Level Cost Text does not work when applying a discount code created by the Group Discount Code Add On.

A workaround is to apply the discount code via the URL query parameter, that works but does not work when using the AJAX apply discount code feature.

**Comment by andrewlimaza** [comment]
Having issues replicating it, will look into this further as well and asked for more information...

**Comment by JarrydLong** [comment]
Tested and cannot replicate, the discount and text applies as expected. 

Tested using: 

PMPro 2.9.8
Level Cost Text 0.3.2
Group Discounts: 0.3.2
