### ISSUE TITLE
Bug: Conflict with Addon Package plugin. Displays custom text on Addon Price

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-level-cost-text#22]
When using Custome Level Cost Text, the **custom text** from the required levels shows on the Addon Package checkout.
![Screen Shot 2022-02-18 at 9 25 33 AM](https://user-images.githubusercontent.com/8083630/154702681-3e51b046-c05d-4008-8dde-fe0732a9e817.png)

![Screen Shot 2022-02-18 at 9 29 16 AM](https://user-images.githubusercontent.com/8083630/154702933-ab0b08a9-1b9e-4019-8b7b-c4f063eb9dbd.png)

Addon Packages should NOT show this custom text.

Also happens when Level is bundled with A
![Screen Shot 2022-02-18 at 9 34 26 AM](https://user-images.githubusercontent.com/8083630/154702529-c0174d2c-e6ea-4704-8d5b-a6ec8cc057b6.png)
ddon Package:

**Comment by JarrydLong** [comment]
Tested this and have been unable to replicate. The correct pricing now shows on checkout when attempting to purchase an Add On package. 

Tested using:

PMPro 2.9.8
Level Cost Text 0.3.2
Add On Packages 0.8
