### ISSUE TITLE
Bug: Hide Unnecessary Decimals not working for one time payments

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-level-cost-text#38]
**Describe the bug**
Selecting "Hide Unnecessary Decimals" works on recurring subscription pricing, but the extra .00 still shows up for any level with no recurring payments.

I have checked how the price was added, and no .00 was included in the pricing.

**To Reproduce**
1. Go to Advanced Settings in PMPro
2. Select "Yes" to Hide unnecessary decimals.
3. View Level Page

**Screenshots**
![Screenshot 2024-01-29 at 8 31 07 AM](https://github.com/strangerstudios/pmpro-level-cost-text/assets/8083630/a6a605bb-6ffd-44e3-a6b4-cb2640156653)

**Expected behavior**
All prices should exclude .00 

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only the Paid Memberships Pro plugin is active.
- [ x] This bug happens with a default WordPress theme active or [Memberlite](https://wordpress.org/themes/memberlite/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
PMPro - 2.12.8 
WordPress - 6.4.2
Custom Level Cost Text Add On -  0.4.1

</details>

**Comment by andrewlimaza** [comment]
This has been resolved in latest commit to `dev` branch and should go out soon.
