### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by wbgraphics** [strangerstudios/pmpro-level-cost-text#8]
Hi,

I think I've encountered a bug in PMPro with Custom Level Text.
This occurs when PMPro is used with "Custom Level Text" addon and the "Remove unnecessary decimals" option is set to "Yes". When I set it to "No" everything works ok.

If I set the membership price to:
$1000 - it displays $10
$1001 - it displays $11
$1002 - it displays $12
$1003 - it displays $13
$1004 - it displays $14
$1005 - it displays $15... and so on
or to $100000 it displays $1000.

In the membership details the price is $1000, but on memberships list, on the frontend and in checkout it is $10. It seems like the plugin takes "00" in the middle as unnecessary decimals and cuts it. I hope this will be helpful.

Victor

**Comment by ideadude** [comment]
This commit should fix it https://github.com/strangerstudios/pmpro-level-cost-text/commit/347178a86e78b9079ceec5a26274abaa40e8000c maybe some of the other recent updates too. I'm going to publish a release in a moment. Let me know if this is still happening.

The str_replace stuff we do (are still doing for some of the other options) can break in certain edge cases. We will work on getting those fixed up.
